# -*- coding: utf-8 -*-
"""project_cfai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_MHYCa1-fPXS4bk3os6EZewv4hgV-A-Z
"""

!pip install gradio

import gradio as gr
import heapq

# =====================================================
# PARKING SLOT DATABASE
# =====================================================

parking_slots = {

    "A1": {"type":"Car","status":"Free","distance":2},
    "A2": {"type":"Car","status":"Occupied","distance":4},
    "A3": {"type":"Car","status":"Free","distance":1},

    "B1": {"type":"Bike","status":"Free","distance":5},
    "B2": {"type":"Bike","status":"Occupied","distance":2},

    "C1": {"type":"Truck","status":"Free","distance":3},
}

# =====================================================
# HEURISTIC FUNCTION
# =====================================================

def heuristic(slot):

    return parking_slots[slot]["distance"]

# =====================================================
# CSP VALIDATION
# =====================================================

def is_valid(slot, vehicle_type):

    if parking_slots[slot]["status"] != "Free":
        return False

    if parking_slots[slot]["type"] != vehicle_type:
        return False

    return True

# =====================================================
# SLOT RECOMMENDATION
# =====================================================

def recommend_slot(vehicle_no, vehicle_type):

    possible_slots = []

    for slot in parking_slots:

        if is_valid(slot, vehicle_type):

            cost = heuristic(slot)

            heapq.heappush(possible_slots, (cost, slot))

    if len(possible_slots) == 0:

        message = "No Parking Slot Available"

    else:

        best_slot = heapq.heappop(possible_slots)[1]

        parking_slots[best_slot]["status"] = "Reserved"

        message = f"AI Recommended Slot : {best_slot}"

    return create_website(message)

# =====================================================
# WEBSITE DESIGN
# =====================================================

def create_website(message):

    slot_html = ""

    for slot in parking_slots:

        status = parking_slots[slot]["status"]

        if status == "Free":
            color = "#16a34a"

        elif status == "Occupied":
            color = "#dc2626"

        else:
            color = "#ca8a04"

        slot_html += f"""

        <div style='
        background:{color};
        padding:25px;
        border-radius:15px;
        text-align:center;
        font-size:22px;
        font-weight:bold;
        box-shadow:0 0 15px rgba(0,0,0,0.4);
        '>

        {slot}

        <br><br>

        <span style='font-size:15px'>
        {status}
        </span>

        </div>
        """

    html = f"""

    <html>

    <head>

    <style>

    body{{
        background:#081120;
        color:white;
        font-family:Arial;
        padding:20px;
    }}

    .title{{
        text-align:center;
        font-size:40px;
        color:#00d9ff;
        margin-bottom:30px;
        font-weight:bold;
    }}

    .card{{
        background:linear-gradient(135deg,#1b4332,#2d6a4f);
        padding:30px;
        border-radius:20px;
        margin-bottom:30px;
        box-shadow:0 0 20px rgba(0,217,255,0.3);
    }}

    .grid{{
        display:grid;
        grid-template-columns:repeat(3,1fr);
        gap:20px;
    }}

    .message{{
        margin-top:30px;
        font-size:24px;
        color:#00ffcc;
        text-align:center;
        font-weight:bold;
    }}

    </style>

    </head>

    <body>

    <div class='title'>
    🚗 ParkAI — Automated Parking Management System
    </div>

    <div class='card'>

    <h2>Vehicle Information</h2>

    <p><b>CO1:</b> PEAS Agent Model</p>
    <p><b>CO2:</b> Heuristic & Greedy Search</p>
    <p><b>CO3:</b> CSP Constraint Satisfaction</p>

    </div>

    <div class='card'>

    <h2>Parking Slots</h2>

    <div class='grid'>

    {slot_html}

    </div>

    <div class='message'>

    {message}

    </div>

    </div>

    </body>

    </html>

    """

    return html

# =====================================================
# INITIAL WEBSITE
# =====================================================

initial_page = create_website("System Ready")

# =====================================================
# GRADIO UI
# =====================================================

demo = gr.Interface(

    fn=recommend_slot,

    inputs=[

        gr.Textbox(
            label="Vehicle Number"
        ),

        gr.Dropdown(
            ["Car","Bike","Truck"],
            label="Vehicle Type",
            value="Car"
        )

    ],

    outputs=gr.HTML(),

    title="ParkAI - AI Parking System"
)

demo.launch(share=True)